arch: xception
num_classes: 1000
#pretrained: True
fix_fc: True
device_ids: [0, 1]
workers: 3
max_epoch: 10
max_iteration: 2000
batch_size: 1

base_lr: 0.1
lr_decay_factor: 0.1
lr_decay_epoch: 2
lr_lowest: 0.0001

momentum: 0.9
weight_decay: 0.0001

print_freq: 100
validation_freq: 1000
log: report.txt
input_size: 299
train_set: /data/shengqiang/data/new_train_and_test/test_image.txt
test_set: /data/shengqiang/data/new_train_and_test/test_image.txt
  
